[project]
name = "wagtail-belajar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.1",
    "django-stubs>=5.2.9",
    "wagtail>=7.2.1",
]
